#### Startup
print('setting up folder & file variables')

##### -------- Folders ------- ######
RESULTS_DIR<-file.path(getwd(),'RESULTS')
PUB_PACKAGE_DIR<-file.path(getwd(),'_PUBLICATION_ASSETS')
DATA_DIR<-file.path(getwd(),'DATA')
EXT_DATA_DIR<-file.path(DATA_DIR,'EXTERNAL')
IBCSO_DATA_DIR<-file.path(EXT_DATA_DIR,'IBCSO')
CURRENTS_DATA_DIR<-file.path(EXT_DATA_DIR,'COPERNICUS_CURRENTS')

OCEANOGRAPHY_DIR<-file.path(DATA_DIR,'MSM115_Oceanography')
KRILL_DIR<-file.path(DATA_DIR,'MSM115_Krill')
CET_DIR<-file.path(DATA_DIR,'MSM115_Cetaceans')

GFX_DIR<-file.path(getwd(),'GFX')
dir.create(GFX_DIR, showWarnings = F, recursive = T)
dir.create(RESULTS_DIR, showWarnings = F, recursive = T)
dir.create(PUB_PACKAGE_DIR, showWarnings = F, recursive = T)

##### -------- Files ------- ######
### RData files

# RESULTS
MSM115_KRILL_ABU_DATA<-file.path(RESULTS_DIR,'MSM115_KRILL_ABUNDANCE.RData')
MSM115_KRILL_COMPLETE_DATA<-file.path(RESULTS_DIR,'MSM115_KRILL_COMPLETE.RData')
MSM115_MERGED_CET_NET_OCE_TOPO<-file.path(RESULTS_DIR,'MSM115_CET_NET_OCE_TOPO.RData')
MSM115_DS_RESULT<-file.path(RESULTS_DIR,'MSM115_CET_ABUNDANCE.RData')
MSM115_PCA_DATA<-file.path(RESULTS_DIR,'MSM115_PCA_DATA.RData')
MSM115_CET_ANALYSIS_DATA<-file.path(RESULTS_DIR,'MSM115_Cet_Survey.RData')
SOAP_PARAMETERS<-file.path(RESULTS_DIR,'MSM115_soap_parameters.RData')
MSM115_CLUSTER_DATA<-file.path(RESULTS_DIR,'MSM115_cluster_data.RData')
ENV_DATA_FILE<-file.path(RESULTS_DIR,'MSM115_ENV_DATA.RData')
OCE_DATA_FILE<-file.path(RESULTS_DIR,'MSM115_oceanography.RData')

### Vector Data
# DATA
MSM115_EXPEDITION_DATA<-file.path(DATA_DIR,'MSM115_Expedition.gpkg')
MSM115_SPATIAL_DATA<-file.path(DATA_DIR,'MSM115_vector_data.gpkg')
MSM115_STRATA_FILE<-file.path(CET_DIR,'MSM115_Survey_Strata.gpkg')

# RESULTS
MSM115_KRILL_ABU_GPKG<-file.path(RESULTS_DIR,'MSM115_KRILL_ABUNDANCE.gpkg')
MSM115_KRILL_MULTIMODALITY_GPKG<-file.path(RESULTS_DIR,'MSM115_KRILL_MULTIMODALITY.gpkg')
SOAP_SPATIAL_DATA<-file.path(RESULTS_DIR,'MSM115_soap_vector_data.gpkg')
MSM115_CLUSTER_RESULTS<-file.path(RESULTS_DIR,'MSM115_cluster_data.gpkg')
CURRENTS_STRATA_GPKG<-file.path(RESULTS_DIR,'MSM115_currents_strata.gpkg')

### Raster Data
# DATA
DEPTH_FILE<-file.path(IBCSO_DATA_DIR,'MSM115_IBCSO_ANNUAL_depth.tif')
DIST2SHELF_FILE<-file.path(IBCSO_DATA_DIR,'MSM115_dist2shelf_km.tif')
COPERNICUS_CURRENTS_NC<-file.path(EXT_DATA_DIR,'currents_2023.nc')

# RESULTS
ENV_STACK_MASK_FILE<-file.path(RESULTS_DIR,'MSM115_ENV_STACK_MASK.tif')
ENV_STACK_FILE<-file.path(RESULTS_DIR,'MSM115_ENV_STACK.tif')
OCE_STACK_FILE<-file.path(RESULTS_DIR,'MSM115_OCE_STACK.tif')
PRED_STACK_FILE<-file.path(RESULTS_DIR,'MSM115_cluster_prediction.tif')

### Tabular Data
# DATA
MSM115_KRILL_ABU_FILE<-file.path(KRILL_DIR,'MSM115_Net_trawl_abu.xlsx')
MSM115_KRILL_LENGTH_FILE<-file.path(KRILL_DIR,'MSM115_Net_trawl_lengths.xlsx')
MSM115_CET_SURVEY_DATA<-file.path(CET_DIR,'MSM115_ds_survey.csv')
MSM115_CTD_DATA<-file.path(OCEANOGRAPHY_DIR,'MSM115_oce_data.csv')
MSM115_CET_OPP_DATA<-file.path(CET_DIR,'MSM115_opp_sightings.csv')

# RESULTS
MSM115_KRILL_MULTIMODALITY_FILE<-file.path(RESULTS_DIR,'MSM115_KRLL_MULTIMODALITY.xlsx')
MSM115_KRILL_MULTIMODALITY_CLUSTER_FILE<-file.path(RESULTS_DIR,'MSM115_KRLL_CLUSTER_MULTIMODALITY.xlsx')
MSM115_KRILL_MULTIMODALITY_CLUSTER_NAME_FILE<-file.path(RESULTS_DIR,'MSM115_KRLL_CLUSTER_NAME_MULTIMODALITY.xlsx')
MSM115_KRILL_ABU_SUMMARY_FILE<-file.path(RESULTS_DIR,'MSM115_KRILL_ABU_SUMMARY.xlsx')
MSM115_DS_MODEL_XLSX<-file.path(RESULTS_DIR,'MSM115_DS_model_data.xlsx')
MSM115_DS_MODEL_COV_XLSX<-file.path(RESULTS_DIR,'MSM115_DS_model_cov_mat.xlsx')
MSM115_CET_SIGHTINGS<-file.path(RESULTS_DIR,'MSM115_CET_SIGHTINGS.xlsx')
MSM115_CET_DS_RESULTS<-file.path(RESULTS_DIR,'MSM115_DS_SURVEY_RESULTS.xlsx')
MSM115_CET_DS_SUMMARY_FILE<-file.path(RESULTS_DIR,'MSM115_DS_SURVEY_SUMMARY.xlsx')
MSM115_CET_DS_CANDIDATE_MODELS<-file.path(RESULTS_DIR,'MSM115_DS_DETFCT_CANDIDATES.xlsx')
MSM115_CLUSTER_CLASSIFICATION_FILE<-file.path(RESULTS_DIR,'MSM115_CLUSTER_CLASS.xlsx')
MSM115_STATION_SUMMARY_FILE<-file.path(RESULTS_DIR,'MSM115_STATION_SUMMARY.xlsx')
